# Generated by Django 4.0.3 on 2023-07-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Customer',
            new_name='customer',
        ),
    ]
