# Generated by Django 4.0.3 on 2023-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_reason_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
